name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: tourbuddy_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Backend Dependencies
        run: |
          cd backend
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Set up Laravel Environment
        run: |
          cd backend
          cp .env.example .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=tourbuddy_db" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=" >> .env
          php artisan key:generate

      - name: Set Laravel Permissions
        run: |
          cd backend
          chmod -R 777 storage bootstrap/cache

      - name: Wait for MySQL to be Ready
        run: |
          sleep 10  # Ensures MySQL is up before running migrations

      - name: Run Laravel Migrations
        run: |
          cd backend
          php artisan migrate --force

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: npm-

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run Backend Tests
        run: |
          cd backend
          php artisan test
